QUANTIFY=quantify -cache-dir=/remote/sbg_totalrecall/boq/tmp/quantify_cache/

default:
	g++ -Wall -o a.out -lpthread Dog.cpp Cat.cpp Global.cpp main.cc
	a.out


#${QUANTIFY} c++ -Wall -I../boost/boost_1_45_0 -o a.out -lpthread main.cc
#	g++ -Wall -I../boost/boost_1_45_0 -o a.out -lpthread main.cc
